blank_issues_enabled: true
contact_links:
  - name: Reach out on social media
    url: https://bsky.app/profile/firecube.bsky.social
    about: Ask questions and see progress on Bluesky.
  - name: Question & Discussion
    url: https://dsc.gg/devsanx
    about: Post your questions and join the discussion. You can participate in chats on every channel.
